In [3]:
"Hello World"

'Hello World'

In [2]:
greeting = "Hello World"

In [4]:
greeting

'Hello World'

In [5]:
greeting = "Hello World"
greeting

'Hello World'

In [6]:
print(greeting)

Hello World


In [7]:
a = 2
b = 15

In [8]:
a + b

17

In [9]:
my_sum = a + b

In [11]:
my_sum

17

In [12]:
my_product = a * b

In [13]:
my_product

30

In [14]:
import numpy as np

In [15]:
ages_list = [25, 30, 35, 40, 45]

In [18]:
ages = np.array(ages_list)

In [19]:
ages

array([25, 30, 35, 40, 45])

In [20]:
ages = np.array([25, 30, 35, 40, 45])

In [21]:
ages

array([25, 30, 35, 40, 45])

In [22]:
ages[0]

25

In [23]:
ages[6] #Error :c out of bounds

IndexError: index 6 is out of bounds for axis 0 with size 5

In [24]:
ages[-1]

45

In [25]:
ages[-2]

40

In [26]:
ages[0:4]

array([25, 30, 35, 40])

In [27]:
ages[:4]

array([25, 30, 35, 40])

In [28]:
ages[1:4]

array([30, 35, 40])

In [29]:
ages[1:]

array([30, 35, 40, 45])

In [30]:
ages[:]

array([25, 30, 35, 40, 45])

In [31]:
ages[::2]

array([25, 35, 45])

In [32]:
ages[::-1]

array([45, 40, 35, 30, 25])

In [35]:
ages[ages<40]

array([25, 30, 35])

In [36]:
ages[ages<=40]

array([25, 30, 35, 40])

In [37]:
len(ages)

5

In [38]:
ages_mean = np.mean(ages)

In [39]:
ages_mean

35.0

In [40]:
np.min(ages)

25

In [41]:
np.max(ages)

45